# Generated by Django 4.2.6 on 2023-10-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_review_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
