# Generated by Django 4.2.2 on 2023-07-09 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordslist',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 5, 29, 52, 435213, tzinfo=datetime.timezone.utc)),
        ),
    ]
